package edu.odu.cs.cs350;
public enum TokenKinds {
    KEYWORD, INTEGER_LITERAL, IDENTIFIER, EOF,SEMICOLON,LPAREN,RPAREN,
    LBRACE,RBRACE,LBRACK,RBRACK,COMMA,DOT,EQ,GT,LT,NOT,COMP,QUESTION,COLON,
    EQEQ,LTEQ,GTEQ,NOTEQ,ANDAND,OROR,PLUSPLUS,MINUSMINUS,PLUS,MINUS,MULT,
    DIV,AND,OR,XOR,MOD,LSHIFT,RSHIFT,URSHIFT,PLUSEQ,MINUSEQ,MULTEQ,
    DIVEQ,ANDEQ,OREQ,XOREQ,LSHIFTEQ,RSHIFTEQ,URSHIFTEQ,MODEQ,TICK,HASH,QUOTE
    , CHARACTERLITERAL,ABSTRACT, BOOL, BREAK, BYTE,CASE,CATCH,CHAR,CONTINUE,CONST,CLASS,DO,DOUBLE,
    ELSE,EXTENDS,FINAL,FINALLY,FLOAT,FOR,DEFAULT,IMPLEMENTS,IMPORT,INSTANCEOF,
    INT,INTERFACE,LONG,NATIVE,NEW,GOTO,IF,PUBLIC,SHORT,SUPER,SWITCH,SYCHRONIZED,
    PACKAGE,PRIVATE,PROTECTED,TRANSIENT,RETURN,VOID,STATIC,WHILE,THIS,THROW,THROWS,TRY,VOLATILE,STRICTFP,
    BOOLEAN_LITERAL,NULL_LITERAL,STRING_LITERAL,CHARACTER_LITERAL,FLOATING_POINT_LITERAL,APOS,DIVIDE,AT};

 